### ISSUE TITLE
Is this work completely open source?

### ISSUE THREAD

**Issue by tanlei0** [HuangChiEn/Data_generation#1]
I am interested in this work, but have found that much of it is incomplete and the checkpoints are not available for download, and I would like to know how much of this work has been fully open-sourced ？
If so, can you provide the complete code and checkpoints?

You can contact me via email qinlei@cqu.edu.cn

**Comment by HuangChiEn** [comment]
> I am interested in this work, but have found that much of it is incomplete and the checkpoints are not available for download, and I would like to know how much of this work has been fully open-sourced ？ If so, can you provide the complete code and checkpoints?
> 
> You can contact me via email [qinlei@cqu.edu.cn](mailto:qinlei@cqu.edu.cn)

sorry to say that the code is 'partially' open source, but the checkpoint we trained is not public.

**Comment by HuangChiEn** [comment]
> I am interested in this work, but have found that much of it is incomplete and the checkpoints are not available for download, and I would like to know how much of this work has been fully open-sourced ？ If so, can you provide the complete code and checkpoints?
> 
> You can contact me via email [qinlei@cqu.edu.cn](mailto:qinlei@cqu.edu.cn)

but we're encourage you to have some survey about Semantic Image Synthesis via Diffusion Models (SDM) and latent diffusion model, to achieved the similar application (input sematic mask, output very precise layout image). 

feel free to reopen the issue, if you have other related question. have a good day ~
